### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by missinglink** [jillesvangurp/geoplanet2json#1]
Hi @jillesvangurp 

I was hoping to download your pre-processed torrent file but the torrent seems to be unavailable after 5 years.

Do you possibly have an alternative way to download the file which would allow me to skip generating it myself?

Cheers,
-P

**Comment by missinglink** [comment]
Alternatively do you possibly still have a copy of the 'flick shapes' file?

I found the geoplanet file here https://archive.org/download/geoplanet_data_7.10.0.zip/geoplanet_data_7.10.0.zip but not the 'flick shapes' :(

**Comment by missinglink** [comment]
Think I got it, is this the correct file? http://h.yimg.com/ce/flickr/shapes/flickr_shapes_public_dataset_2.0.1.tar.gz

**Comment by jillesvangurp** [comment]
Sorry, I no longer have any of these files; it's indeed quite long ago and the data would have been stale in any case. It's also been ages since I had this project working and I suspect it would be a bit of work to get it up and running again. It's something I'd love to have time to do but seems to be not doable right now for me. 

The flickr shapes file looks like it is correct. As I recall it was quite low quality data. I recommend you try to get your hands on quattroshapes from foursquare if that's still around. They had quite good neighborhood data for some parts of the world as I recall. Sadly their attempts at open data stalled right after they announced that in 2013.

Also, you might be interested in https://github.com/whosonfirst-data/whosonfirst-data, it's an attempt to curate quality geo data, including geojson shapes if I understand correctly. One of my friends @vicchi has been working on this recently (he's ex Yahoo Geoplanet and looking to resurrect that). He might be able to point you to other data sources as well.

**Comment by missinglink** [comment]
Thanks

**Comment by vicchi** [comment]
@missinglink - @jillesvangurp is absolutely right. Who’s On First is WhereOnEarth/Geoplanet on steroids, all in GeoJSON with hierarchies and polygons. Check out whosonfirst.org as a good starting point.

**Comment by missinglink** [comment]
Yes, thank you, I am already aware of WOF from my work on Pelias.

I was interested if there was any historical value to this data it's likely that Aaron merged most/all of it in to WOF already since he was working at Flickr prior to Mapzen.
